export const ADMIN_SIGNIN_REQUEST = 'ADMIN_SIGNIN_REQUEST'
export const ADMIN_SIGNIN_SUCCESS = 'ADMIN_SIGNIN_SUCCESS'
export const ADMIN_SIGNIN_FAIL = 'ADMIN_SIGNIN_FAIL'
export const ADMIN_SIGNOUT = 'ADMIN_SIGNIN_SIGNOUT'
